Fix `getRequiredRequestBodyAsText`
apple/swift-openapi-runtime pull request #20
Opened 2023-06-16 10:25 UTC by sikevux

### Motivation

`getRequiredRequestBodyAsText` currently returns `C?` instead of `C`. As the value should be required an optional in the return is causing issues.

The errors are `Cannot convert value of type 'C?' to specified type` and `Cannot infer contextual base in reference to member 'text'`

 ### Modifications

Change the return type of `getRequiredRequestBodyAsText`

 ### Result

Code using a required requestBody now compiles without errors.

2023-06-16 10:58 UTC, czechboy0 commented
Thanks for the fix, this was an oversight on my part.

2023-06-16 10:58 UTC, czechboy0 approved these changes

2023-06-17 08:28 UTC, simonjbeaumont commented
@swift-server-bot test this please

2023-06-17 08:30 UTC, simonjbeaumont commented
@sikevux this is great, thank you. Is it possible to add a test case for this? Specifically something that uses the code that previously world not compile?

2023-06-17 09:07 UTC, czechboy0 commented
Agreed, we have tests already, but adding one that does something like

`let foo: String = try get...` should do the trick - should not compile without the fix, and should with.

2023-06-17 10:31 UTC, czechboy0 requested changes
Marking as needs work based on the conversation above.

2023-06-17 15:05 UTC, czechboy0 commented
Ugh, I took a quick look and we have the same issue in a few more places:
- https://github.com/apple/swift-openapi-runtime/blob/bec8d38be0254a59baca6e6434823f77cf1d734c/Sources/OpenAPIRuntime/Conversion/Converter%2BCommon.swift#L166
- https://github.com/apple/swift-openapi-runtime/blob/bec8d38be0254a59baca6e6434823f77cf1d734c/Sources/OpenAPIRuntime/Conversion/Converter%2BCommon.swift#L222
- https://github.com/apple/swift-openapi-runtime/blob/bec8d38be0254a59baca6e6434823f77cf1d734c/Sources/OpenAPIRuntime/Conversion/Converter%2BServer.swift#L205

Can you please fix those too? 🙏

2023-06-17 17:43 UTC, sikevux commented
> Ugh, I took a quick look and we have the same issue in a few more places:
> 
> * https://github.com/apple/swift-openapi-runtime/blob/bec8d38be0254a59baca6e6434823f77cf1d734c/Sources/OpenAPIRuntime/Conversion/Converter%2BCommon.swift#L166
> * https://github.com/apple/swift-openapi-runtime/blob/bec8d38be0254a59baca6e6434823f77cf1d734c/Sources/OpenAPIRuntime/Conversion/Converter%2BCommon.swift#L222
> * https://github.com/apple/swift-openapi-runtime/blob/bec8d38be0254a59baca6e6434823f77cf1d734c/Sources/OpenAPIRuntime/Conversion/Converter%2BServer.swift#L205
> 
> Can you please fix those too? 🙏

Yeah. Modified all the `get` tests to explicitly set the type just to make sure there's no more. Seems to be all of them now 😸

2023-06-17 20:47 UTC, czechboy0 approved these changes
Great, thank you!

2023-06-18 09:13 UTC, simonjbeaumont approved these changes
Awesome. Thanks @sikevux!

2023-06-18 09:15 UTC, merged