Support nested values in OpenAPIObjectContainer
apple/swift-openapi-runtime pull request #24
Opened 2023-07-13 04:42 UTC by rboyce

### Motivation

Trying to encode an `OpenAPIValueContainer` would previously throw an `EncodingError` if the untyped container contained nested dictionary or array structures. (e.g. `{"dict": {"foo": "bar"}}`) Data could be decoded into this format, but it could not be re-encoded successfully.

### Modifications

When encoding the value of a nested JSON array or object in `OpenAPIValueContainer`, we now handle arrays and dicts by wrapping the inner value in `OpenAPIValueContainer` before passing it to the encoder. 
(note: Based on the rest of the `encode()` implementation, it seems that this may have been expected to happen previously during decoding. Let me know if making changes on the decode side of things is preferable.)

### Result

Additional unit tests added to validate that encoder generates correct output for nested data structures in `OpenAPIValueContainer`, and that these data structures can be decoded and successfully re-endcoded afterward.

### Test Plan

Run `Test_CodableExtensions` tests, see all tests pass.

2023-07-13 08:01 UTC, simonjbeaumont commented
@swift-server-bot add to allowlist

2023-07-13 08:38 UTC, simonjbeaumont approved these changes
@rboyce Thanks for the patch—and for adding some tests for it.

2023-07-13 08:38 UTC, simonjbeaumont commented on Sources/OpenAPIRuntime/Base/OpenAPIValue.swift
> +            )
Couple of suggestions here:

- We'll be landing #22 soon which means that you'll need to use existential any, i.e. `any Sendable` in place of `Sendable`, so we may as well get it right here so it doesn't need updating again.
- The rest of the switch statement follows a different style of passing `init(unvalidatedValue:)` to `map` and `mapValues` directly, so could we keep it consistent with these new switch cases?

```suggestion
        case let value as [(any Sendable)?]:
            try container.encode(value.map(OpenAPIValueContainer.init(unvalidatedValue:)))
        case let value as [String: (any Sendable)?]:
            try container.encode(value.mapValues(OpenAPIValueContainer.init(unvalidatedValue:)))
```

2023-07-13 08:40 UTC, simonjbeaumont requested changes
Oops, meant to mark as "Request changes", with some minor fixups in https://github.com/apple/swift-openapi-runtime/pull/24/files#r1262219996.

2023-07-17 11:29 UTC, czechboy0 commented
@rboyce Okay I landed the base unit tests - if you'd like, you could port your additional unit tests to the new place (`Test_OpenAPIValue.swift`). 🙏 Thanks

2023-07-17 23:38 UTC, rboyce commented
Rebased past #25. This PR now just contains the additional unit tests for mixed nested values; thanks for the fix @czechboy0!

2023-07-18 06:21 UTC, czechboy0 requested changes

2023-07-18 06:21 UTC, czechboy0 commented on Tests/OpenAPIRuntimeTests/Base/Test_OpenAPIValue.swift
> +            XCTAssertEqual(
Please make it consistent with the other tests by using the utility functions that does the encoding/decoding and equality checks.

2023-07-18 06:21 UTC, czechboy0 commented on Tests/OpenAPIRuntimeTests/Base/Test_OpenAPIValue.swift
> +        do {
Why is this extra do scope here?

2023-07-18 06:21 UTC, czechboy0 commented on Tests/OpenAPIRuntimeTests/Base/Test_OpenAPIValue.swift
> +        do {
Same here about the do scope.

2023-07-18 06:21 UTC, czechboy0 commented
Thanks, please also update the PR description to reflect the remaining changes.

2023-08-03 20:48 UTC, czechboy0 approved these changes
Looks good overall, I'll open another PR bringing it to our style in a bit.

2023-08-03 20:52 UTC, merged

2023-08-03 20:59 UTC, czechboy0 commented
Fixing up the style: https://github.com/apple/swift-openapi-runtime/pull/33