Support base64-encoded data
apple/swift-openapi-runtime pull request #55
Opened 2023-09-26 12:28 UTC by rnro

### Motivation

OpenAPI supports base64-encoded data but to this point OpenAPI Generator has not (https://github.com/apple/swift-openapi-generator/issues/11).

### Modifications

Introduce the `Base64EncodedData` codable type to allow users in the generator to describe byte types which must be en/de-coded.

### Result

Users will be able to describe base64-encoded data as `OpenAPIRuntime.Base64EncodedData` e.g.
```
public typealias MyData = OpenAPIRuntime.Base64EncodedData
```

### Test Plan

Added a round-trip encode/decode test `testEncodingDecodingRoundTrip_base64_success`

2023-09-26 14:13 UTC, rnro commented on Tests/OpenAPIRuntimeTests/Base/Test_OpenAPIValue.swift
> +            try JSONDecoder().decode(Base64EncodedData.self, from: JSONEncoder().encode(encodedData)),
The reason I built it this way is that it was tricky to get hold of an `Encoder`/`Decoder` to inject into the `Base64EncodedData` type directly. 

I confirmed that the code as written calls through to the `init` and `encode` functions of `Base64EncodedData`, I presume delegated by the `JSONEncoder` when it encounters the type.

2023-09-26 15:05 UTC, rnro commented
> By users, do we mean the generator will emit this type alias when it encounters `format: base64` in the OpenAPI document?

Sorry, yes, the generator. I _think_ we will use `format: byte` though as that's mentioned in the [3.03 spec](https://spec.openapis.org/oas/v3.0.3)

2023-09-26 15:40 UTC, czechboy0 commented
@swift-server-bot add to allowlist

2023-10-04 16:39 UTC, rnro commented
@swift-server-bot test this please

2023-10-05 07:20 UTC, czechboy0 commented on Sources/OpenAPIRuntime/Base/Base64EncodedData.swift
> +public struct Base64EncodedData: Sendable, Codable, Hashable {
Please add docs for all public symbols, ideally also with info how to use this type (create and consume).

2023-10-05 15:42 UTC, czechboy0 requested changes
A few minor requests, otherwise looks good! Could you also open a PR of the generator changes, so that we can review both before we start landing them? That's our usual workflow. That means that locally you need to develop the two branches together.

2023-10-05 15:42 UTC, czechboy0 commented on Sources/OpenAPIRuntime/Base/Base64EncodedData.swift
> +/// However more commonly the decoding initializer would be called by a decoder e.g.
```suggestion
/// However more commonly the decoding initializer would be called by a decoder, for example:
```

2023-10-05 15:42 UTC, czechboy0 commented on Sources/OpenAPIRuntime/Base/Base64EncodedData.swift
> +    /// data to be encoded
```suggestion
    /// A container of the raw bytes.
```

2023-10-05 15:42 UTC, czechboy0 commented on Sources/OpenAPIRuntime/Base/Base64EncodedData.swift
> +    public init(from decoder: any Decoder) throws {
```suggestion
    public init(from decoder: any Decoder) throws {
```

We skip documenting conformances.

2023-10-05 15:42 UTC, czechboy0 commented on Sources/OpenAPIRuntime/Base/Base64EncodedData.swift
> +    public func encode(to encoder: any Encoder) throws {
```suggestion
    public func encode(to encoder: any Encoder) throws {
```

Same here.

2023-10-05 15:42 UTC, czechboy0 commented on Sources/OpenAPIRuntime/Errors/RuntimeError.swift
> +            return "Invalid base64-encoded string: '\(string)'"
Let's cap how many bytes we'd actually print.
```suggestion
            return "Invalid base64-encoded string (first 128 bytes): '\(string.prefix(128))'"
```

2023-10-06 09:12 UTC, rnro commented
The accompanying generator change is https://github.com/apple/swift-openapi-generator/pull/326

2023-10-09 14:49 UTC, czechboy0 commented
@swift-server-bot add to allowlist

2023-10-09 14:49 UTC, czechboy0 approved these changes
Lgtm, just rerunning the integration test which should pass now that 0.3.0 has been released.

2023-10-09 14:54 UTC, simonjbeaumont approved these changes
Nice—thanks @rnro !

2023-10-10 07:55 UTC, merged