Add a hook for intercepting decoding errors
apple/swift-openapi-runtime pull request #99
Opened 2024-02-04 02:58 UTC by jpsim

### Motivation

It's useful for clients to be able to have a centralized way to handle decoding errors, which can be useful for logging or telemetry.

See https://github.com/apple/swift-openapi-generator/issues/522 for more discussion on this.

### Modifications

Add a new `DecodingErrorHandler` protocol which has a single `willThrow(_ error: any Error)` requirement.

A decoding handler can be passed to the client configuration on initialization.

This is just a proof-of-concept, if this direction is reasonable, it should be fleshed out to handle all decoding paths.

### Result

With this change, errors produced by body decoders can be intercepted in a centralized way for all methods going through the `Client`.

### Test Plan

I added a simple unit test. More tests would need to be added to sufficiently cover the functionality being introduced here.

2024-04-03 06:39 UTC, czechboy0 reviewed
Looks great overall, apologies for the delay on this PR, it somehow slipped through unnoticed.

2024-04-03 06:39 UTC, czechboy0 commented on Sources/OpenAPIRuntime/Conversion/Configuration.swift
> +    func willThrow(_ error: any Error)
Would you be interested in the context this was thrown in? See `ClientError` and `ServerError`, where we add more context.

2024-04-03 06:39 UTC, czechboy0 commented on Sources/OpenAPIRuntime/Conversion/Configuration.swift
> +        decodingErrorHandler: (any DecodingErrorHandler)? = nil
Looks good, please just add a deprecated 2-parameter version of this initializer in Deprecated.swift, as adding a param is technically a source break. Similar to https://github.com/apple/swift-openapi-runtime/pull/102#discussion_r1547909598

2024-10-03 17:31 UTC, czechboy0 commented
Hi @jpsim - are you still interested in a solution here? I'm happy with either you picking this up again, or letting us take over. It'd just be good to finalize the details with a concrete use case in mind.

2024-11-22 14:06 UTC, czechboy0 requested changes
Marking as waiting on @jpsim for now

2025-01-15 20:42 UTC, jpsim commented
I won't be pursuing this further.

2025-01-15 20:42 UTC, closed without merging

2025-01-15 20:49 UTC, czechboy0 commented
> I won't be pursuing this further. 

May I ask if it's because you found a workflow where you don't need it, or if you don't have the bandwidth to drive the PR?

2025-01-17 16:27 UTC, daviduzumeri commented
We're using this library pretty heavily and this would be a fantastic addition that would help us catch a lot of stuff in Datadog instead of finding out API responses aren't decoding properly from customer complaints.

2025-01-17 20:37 UTC, czechboy0 commented
We're open to this enhancement, and with JP closing this PR, I think it'd be appropriate for someone else to open a new PR and we can discuss next steps there.